// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ack.proto

package game.message;

public final class AckMessage {
  private AckMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Ack2ServerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 ackId = 1;
    /**
     * <code>required int32 ackId = 1;</code>
     *
     * <pre>
     *已经收到消息的最大Id
     * </pre>
     */
    boolean hasAckId();
    /**
     * <code>required int32 ackId = 1;</code>
     *
     * <pre>
     *已经收到消息的最大Id
     * </pre>
     */
    int getAckId();
  }
  /**
   * Protobuf type {@code Ack.Ack2Server}
   *
   * <pre>
   *客户端发给服务器的确认消息
   * </pre>
   */
  public static final class Ack2Server extends
      com.google.protobuf.GeneratedMessage
      implements Ack2ServerOrBuilder {
    // Use Ack2Server.newBuilder() to construct.
    private Ack2Server(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Ack2Server(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Ack2Server defaultInstance;
    public static Ack2Server getDefaultInstance() {
      return defaultInstance;
    }

    public Ack2Server getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Ack2Server(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ackId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.AckMessage.internal_static_Ack_Ack2Server_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.AckMessage.internal_static_Ack_Ack2Server_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.AckMessage.Ack2Server.class, game.message.AckMessage.Ack2Server.Builder.class);
    }

    public static com.google.protobuf.Parser<Ack2Server> PARSER =
        new com.google.protobuf.AbstractParser<Ack2Server>() {
      public Ack2Server parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ack2Server(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Ack2Server> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Ack.Ack2Server.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 926201;</code>
       */
      eMsgID(0, 926201),
      ;

      /**
       * <code>eMsgID = 926201;</code>
       */
      public static final int eMsgID_VALUE = 926201;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 926201: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.AckMessage.Ack2Server.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Ack.Ack2Server.MsgID)
    }

    private int bitField0_;
    // required int32 ackId = 1;
    public static final int ACKID_FIELD_NUMBER = 1;
    private int ackId_;
    /**
     * <code>required int32 ackId = 1;</code>
     *
     * <pre>
     *已经收到消息的最大Id
     * </pre>
     */
    public boolean hasAckId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 ackId = 1;</code>
     *
     * <pre>
     *已经收到消息的最大Id
     * </pre>
     */
    public int getAckId() {
      return ackId_;
    }

    private void initFields() {
      ackId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAckId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ackId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ackId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.AckMessage.Ack2Server parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.AckMessage.Ack2Server parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.AckMessage.Ack2Server parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.AckMessage.Ack2Server parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.AckMessage.Ack2Server parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.AckMessage.Ack2Server parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.AckMessage.Ack2Server parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.AckMessage.Ack2Server parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.AckMessage.Ack2Server parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.AckMessage.Ack2Server parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.AckMessage.Ack2Server prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Ack.Ack2Server}
     *
     * <pre>
     *客户端发给服务器的确认消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.AckMessage.Ack2ServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.AckMessage.internal_static_Ack_Ack2Server_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.AckMessage.internal_static_Ack_Ack2Server_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.AckMessage.Ack2Server.class, game.message.AckMessage.Ack2Server.Builder.class);
      }

      // Construct using game.message.AckMessage.Ack2Server.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ackId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.AckMessage.internal_static_Ack_Ack2Server_descriptor;
      }

      public game.message.AckMessage.Ack2Server getDefaultInstanceForType() {
        return game.message.AckMessage.Ack2Server.getDefaultInstance();
      }

      public game.message.AckMessage.Ack2Server build() {
        game.message.AckMessage.Ack2Server result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.AckMessage.Ack2Server buildPartial() {
        game.message.AckMessage.Ack2Server result = new game.message.AckMessage.Ack2Server(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ackId_ = ackId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.AckMessage.Ack2Server) {
          return mergeFrom((game.message.AckMessage.Ack2Server)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.AckMessage.Ack2Server other) {
        if (other == game.message.AckMessage.Ack2Server.getDefaultInstance()) return this;
        if (other.hasAckId()) {
          setAckId(other.getAckId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAckId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.AckMessage.Ack2Server parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.AckMessage.Ack2Server) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 ackId = 1;
      private int ackId_ ;
      /**
       * <code>required int32 ackId = 1;</code>
       *
       * <pre>
       *已经收到消息的最大Id
       * </pre>
       */
      public boolean hasAckId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 ackId = 1;</code>
       *
       * <pre>
       *已经收到消息的最大Id
       * </pre>
       */
      public int getAckId() {
        return ackId_;
      }
      /**
       * <code>required int32 ackId = 1;</code>
       *
       * <pre>
       *已经收到消息的最大Id
       * </pre>
       */
      public Builder setAckId(int value) {
        bitField0_ |= 0x00000001;
        ackId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ackId = 1;</code>
       *
       * <pre>
       *已经收到消息的最大Id
       * </pre>
       */
      public Builder clearAckId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ackId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Ack.Ack2Server)
    }

    static {
      defaultInstance = new Ack2Server(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Ack.Ack2Server)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Ack_Ack2Server_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Ack_Ack2Server_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tAck.proto\022\003Ack\"2\n\nAck2Server\022\r\n\005ackId\030" +
      "\001 \002(\005\"\025\n\005MsgID\022\014\n\006eMsgID\020\371\3038B\032\n\014game.mes" +
      "sageB\nAckMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Ack_Ack2Server_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Ack_Ack2Server_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Ack_Ack2Server_descriptor,
              new java.lang.String[] { "AckId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
