// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseMessage.proto

package game.message;

public final class BaseMessage {
  private BaseMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RpcOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .BaseMessage.RpcData rpcData = 1;
    /**
     * <code>required .BaseMessage.RpcData rpcData = 1;</code>
     */
    boolean hasRpcData();
    /**
     * <code>required .BaseMessage.RpcData rpcData = 1;</code>
     */
    game.message.BaseMessage.RpcData getRpcData();
    /**
     * <code>required .BaseMessage.RpcData rpcData = 1;</code>
     */
    game.message.BaseMessage.RpcDataOrBuilder getRpcDataOrBuilder();
  }
  /**
   * Protobuf type {@code BaseMessage.Rpc}
   *
   * <pre>
   * 最终发送数据协议(注:这里本应该是一个repeated结构,编译发送多个二进制消息, 后面需要修改)
   * </pre>
   */
  public static final class Rpc extends
      com.google.protobuf.GeneratedMessage
      implements RpcOrBuilder {
    // Use Rpc.newBuilder() to construct.
    private Rpc(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Rpc(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Rpc defaultInstance;
    public static Rpc getDefaultInstance() {
      return defaultInstance;
    }

    public Rpc getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Rpc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              game.message.BaseMessage.RpcData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = rpcData_.toBuilder();
              }
              rpcData_ = input.readMessage(game.message.BaseMessage.RpcData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rpcData_);
                rpcData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.BaseMessage.internal_static_BaseMessage_Rpc_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.BaseMessage.internal_static_BaseMessage_Rpc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.BaseMessage.Rpc.class, game.message.BaseMessage.Rpc.Builder.class);
    }

    public static com.google.protobuf.Parser<Rpc> PARSER =
        new com.google.protobuf.AbstractParser<Rpc>() {
      public Rpc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Rpc(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Rpc> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .BaseMessage.RpcData rpcData = 1;
    public static final int RPCDATA_FIELD_NUMBER = 1;
    private game.message.BaseMessage.RpcData rpcData_;
    /**
     * <code>required .BaseMessage.RpcData rpcData = 1;</code>
     */
    public boolean hasRpcData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .BaseMessage.RpcData rpcData = 1;</code>
     */
    public game.message.BaseMessage.RpcData getRpcData() {
      return rpcData_;
    }
    /**
     * <code>required .BaseMessage.RpcData rpcData = 1;</code>
     */
    public game.message.BaseMessage.RpcDataOrBuilder getRpcDataOrBuilder() {
      return rpcData_;
    }

    private void initFields() {
      rpcData_ = game.message.BaseMessage.RpcData.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRpcData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getRpcData().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, rpcData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, rpcData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.BaseMessage.Rpc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.BaseMessage.Rpc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.BaseMessage.Rpc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.BaseMessage.Rpc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.BaseMessage.Rpc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.BaseMessage.Rpc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.BaseMessage.Rpc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.BaseMessage.Rpc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.BaseMessage.Rpc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.BaseMessage.Rpc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.BaseMessage.Rpc prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseMessage.Rpc}
     *
     * <pre>
     * 最终发送数据协议(注:这里本应该是一个repeated结构,编译发送多个二进制消息, 后面需要修改)
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.BaseMessage.RpcOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.BaseMessage.internal_static_BaseMessage_Rpc_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.BaseMessage.internal_static_BaseMessage_Rpc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.BaseMessage.Rpc.class, game.message.BaseMessage.Rpc.Builder.class);
      }

      // Construct using game.message.BaseMessage.Rpc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRpcDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (rpcDataBuilder_ == null) {
          rpcData_ = game.message.BaseMessage.RpcData.getDefaultInstance();
        } else {
          rpcDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.BaseMessage.internal_static_BaseMessage_Rpc_descriptor;
      }

      public game.message.BaseMessage.Rpc getDefaultInstanceForType() {
        return game.message.BaseMessage.Rpc.getDefaultInstance();
      }

      public game.message.BaseMessage.Rpc build() {
        game.message.BaseMessage.Rpc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.BaseMessage.Rpc buildPartial() {
        game.message.BaseMessage.Rpc result = new game.message.BaseMessage.Rpc(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (rpcDataBuilder_ == null) {
          result.rpcData_ = rpcData_;
        } else {
          result.rpcData_ = rpcDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.BaseMessage.Rpc) {
          return mergeFrom((game.message.BaseMessage.Rpc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.BaseMessage.Rpc other) {
        if (other == game.message.BaseMessage.Rpc.getDefaultInstance()) return this;
        if (other.hasRpcData()) {
          mergeRpcData(other.getRpcData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRpcData()) {
          
          return false;
        }
        if (!getRpcData().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.BaseMessage.Rpc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.BaseMessage.Rpc) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .BaseMessage.RpcData rpcData = 1;
      private game.message.BaseMessage.RpcData rpcData_ = game.message.BaseMessage.RpcData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          game.message.BaseMessage.RpcData, game.message.BaseMessage.RpcData.Builder, game.message.BaseMessage.RpcDataOrBuilder> rpcDataBuilder_;
      /**
       * <code>required .BaseMessage.RpcData rpcData = 1;</code>
       */
      public boolean hasRpcData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .BaseMessage.RpcData rpcData = 1;</code>
       */
      public game.message.BaseMessage.RpcData getRpcData() {
        if (rpcDataBuilder_ == null) {
          return rpcData_;
        } else {
          return rpcDataBuilder_.getMessage();
        }
      }
      /**
       * <code>required .BaseMessage.RpcData rpcData = 1;</code>
       */
      public Builder setRpcData(game.message.BaseMessage.RpcData value) {
        if (rpcDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          rpcData_ = value;
          onChanged();
        } else {
          rpcDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .BaseMessage.RpcData rpcData = 1;</code>
       */
      public Builder setRpcData(
          game.message.BaseMessage.RpcData.Builder builderForValue) {
        if (rpcDataBuilder_ == null) {
          rpcData_ = builderForValue.build();
          onChanged();
        } else {
          rpcDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .BaseMessage.RpcData rpcData = 1;</code>
       */
      public Builder mergeRpcData(game.message.BaseMessage.RpcData value) {
        if (rpcDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              rpcData_ != game.message.BaseMessage.RpcData.getDefaultInstance()) {
            rpcData_ =
              game.message.BaseMessage.RpcData.newBuilder(rpcData_).mergeFrom(value).buildPartial();
          } else {
            rpcData_ = value;
          }
          onChanged();
        } else {
          rpcDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .BaseMessage.RpcData rpcData = 1;</code>
       */
      public Builder clearRpcData() {
        if (rpcDataBuilder_ == null) {
          rpcData_ = game.message.BaseMessage.RpcData.getDefaultInstance();
          onChanged();
        } else {
          rpcDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .BaseMessage.RpcData rpcData = 1;</code>
       */
      public game.message.BaseMessage.RpcData.Builder getRpcDataBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRpcDataFieldBuilder().getBuilder();
      }
      /**
       * <code>required .BaseMessage.RpcData rpcData = 1;</code>
       */
      public game.message.BaseMessage.RpcDataOrBuilder getRpcDataOrBuilder() {
        if (rpcDataBuilder_ != null) {
          return rpcDataBuilder_.getMessageOrBuilder();
        } else {
          return rpcData_;
        }
      }
      /**
       * <code>required .BaseMessage.RpcData rpcData = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          game.message.BaseMessage.RpcData, game.message.BaseMessage.RpcData.Builder, game.message.BaseMessage.RpcDataOrBuilder> 
          getRpcDataFieldBuilder() {
        if (rpcDataBuilder_ == null) {
          rpcDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              game.message.BaseMessage.RpcData, game.message.BaseMessage.RpcData.Builder, game.message.BaseMessage.RpcDataOrBuilder>(
                  rpcData_,
                  getParentForChildren(),
                  isClean());
          rpcData_ = null;
        }
        return rpcDataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:BaseMessage.Rpc)
    }

    static {
      defaultInstance = new Rpc(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BaseMessage.Rpc)
  }

  public interface RpcDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 msgId = 1;
    /**
     * <code>required int32 msgId = 1;</code>
     */
    boolean hasMsgId();
    /**
     * <code>required int32 msgId = 1;</code>
     */
    int getMsgId();

    // optional bytes serialized_msgData = 2;
    /**
     * <code>optional bytes serialized_msgData = 2;</code>
     */
    boolean hasSerializedMsgData();
    /**
     * <code>optional bytes serialized_msgData = 2;</code>
     */
    com.google.protobuf.ByteString getSerializedMsgData();
  }
  /**
   * Protobuf type {@code BaseMessage.RpcData}
   *
   * <pre>
   * 具体的被序列化为二进制数据的消息协议结构
   * </pre>
   */
  public static final class RpcData extends
      com.google.protobuf.GeneratedMessage
      implements RpcDataOrBuilder {
    // Use RpcData.newBuilder() to construct.
    private RpcData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcData defaultInstance;
    public static RpcData getDefaultInstance() {
      return defaultInstance;
    }

    public RpcData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RpcData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              serializedMsgData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.BaseMessage.internal_static_BaseMessage_RpcData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.BaseMessage.internal_static_BaseMessage_RpcData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.BaseMessage.RpcData.class, game.message.BaseMessage.RpcData.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcData> PARSER =
        new com.google.protobuf.AbstractParser<RpcData>() {
      public RpcData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 msgId = 1;
    public static final int MSGID_FIELD_NUMBER = 1;
    private int msgId_;
    /**
     * <code>required int32 msgId = 1;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 msgId = 1;</code>
     */
    public int getMsgId() {
      return msgId_;
    }

    // optional bytes serialized_msgData = 2;
    public static final int SERIALIZED_MSGDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString serializedMsgData_;
    /**
     * <code>optional bytes serialized_msgData = 2;</code>
     */
    public boolean hasSerializedMsgData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes serialized_msgData = 2;</code>
     */
    public com.google.protobuf.ByteString getSerializedMsgData() {
      return serializedMsgData_;
    }

    private void initFields() {
      msgId_ = 0;
      serializedMsgData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, serializedMsgData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, serializedMsgData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.BaseMessage.RpcData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.BaseMessage.RpcData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.BaseMessage.RpcData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.BaseMessage.RpcData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.BaseMessage.RpcData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.BaseMessage.RpcData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.BaseMessage.RpcData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.BaseMessage.RpcData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.BaseMessage.RpcData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.BaseMessage.RpcData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.BaseMessage.RpcData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseMessage.RpcData}
     *
     * <pre>
     * 具体的被序列化为二进制数据的消息协议结构
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.BaseMessage.RpcDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.BaseMessage.internal_static_BaseMessage_RpcData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.BaseMessage.internal_static_BaseMessage_RpcData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.BaseMessage.RpcData.class, game.message.BaseMessage.RpcData.Builder.class);
      }

      // Construct using game.message.BaseMessage.RpcData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        serializedMsgData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.BaseMessage.internal_static_BaseMessage_RpcData_descriptor;
      }

      public game.message.BaseMessage.RpcData getDefaultInstanceForType() {
        return game.message.BaseMessage.RpcData.getDefaultInstance();
      }

      public game.message.BaseMessage.RpcData build() {
        game.message.BaseMessage.RpcData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.BaseMessage.RpcData buildPartial() {
        game.message.BaseMessage.RpcData result = new game.message.BaseMessage.RpcData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serializedMsgData_ = serializedMsgData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.BaseMessage.RpcData) {
          return mergeFrom((game.message.BaseMessage.RpcData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.BaseMessage.RpcData other) {
        if (other == game.message.BaseMessage.RpcData.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          setMsgId(other.getMsgId());
        }
        if (other.hasSerializedMsgData()) {
          setSerializedMsgData(other.getSerializedMsgData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.BaseMessage.RpcData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.BaseMessage.RpcData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 msgId = 1;
      private int msgId_ ;
      /**
       * <code>required int32 msgId = 1;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 msgId = 1;</code>
       */
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <code>required int32 msgId = 1;</code>
       */
      public Builder setMsgId(int value) {
        bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msgId = 1;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = 0;
        onChanged();
        return this;
      }

      // optional bytes serialized_msgData = 2;
      private com.google.protobuf.ByteString serializedMsgData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes serialized_msgData = 2;</code>
       */
      public boolean hasSerializedMsgData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes serialized_msgData = 2;</code>
       */
      public com.google.protobuf.ByteString getSerializedMsgData() {
        return serializedMsgData_;
      }
      /**
       * <code>optional bytes serialized_msgData = 2;</code>
       */
      public Builder setSerializedMsgData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        serializedMsgData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes serialized_msgData = 2;</code>
       */
      public Builder clearSerializedMsgData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serializedMsgData_ = getDefaultInstance().getSerializedMsgData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BaseMessage.RpcData)
    }

    static {
      defaultInstance = new RpcData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BaseMessage.RpcData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseMessage_Rpc_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BaseMessage_Rpc_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseMessage_RpcData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BaseMessage_RpcData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BaseMessage.proto\022\013BaseMessage\",\n\003Rpc\022" +
      "%\n\007rpcData\030\001 \002(\0132\024.BaseMessage.RpcData\"4" +
      "\n\007RpcData\022\r\n\005msgId\030\001 \002(\005\022\032\n\022serialized_m" +
      "sgData\030\002 \001(\014B\033\n\014game.messageB\013BaseMessag" +
      "e"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BaseMessage_Rpc_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BaseMessage_Rpc_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BaseMessage_Rpc_descriptor,
              new java.lang.String[] { "RpcData", });
          internal_static_BaseMessage_RpcData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_BaseMessage_RpcData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BaseMessage_RpcData_descriptor,
              new java.lang.String[] { "MsgId", "SerializedMsgData", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
