// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Keys.proto

package game.message;

public final class KeysMessage {
  private KeysMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqUseKeyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string token = 1;
    /**
     * <code>optional string token = 1;</code>
     *
     * <pre>
     * 从平台SDK中获取的访问令牌
     * </pre>
     */
    boolean hasToken();
    /**
     * <code>optional string token = 1;</code>
     *
     * <pre>
     * 从平台SDK中获取的访问令牌
     * </pre>
     */
    java.lang.String getToken();
    /**
     * <code>optional string token = 1;</code>
     *
     * <pre>
     * 从平台SDK中获取的访问令牌
     * </pre>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    // required string key = 2;
    /**
     * <code>required string key = 2;</code>
     *
     * <pre>
     * 激活码/兑换码的CODE
     * </pre>
     */
    boolean hasKey();
    /**
     * <code>required string key = 2;</code>
     *
     * <pre>
     * 激活码/兑换码的CODE
     * </pre>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 2;</code>
     *
     * <pre>
     * 激活码/兑换码的CODE
     * </pre>
     */
    com.google.protobuf.ByteString
        getKeyBytes();
  }
  /**
   * Protobuf type {@code Keys.ReqUseKey}
   *
   * <pre>
   *客户端请求使用激活码/兑换码
   * </pre>
   */
  public static final class ReqUseKey extends
      com.google.protobuf.GeneratedMessage
      implements ReqUseKeyOrBuilder {
    // Use ReqUseKey.newBuilder() to construct.
    private ReqUseKey(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqUseKey(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqUseKey defaultInstance;
    public static ReqUseKey getDefaultInstance() {
      return defaultInstance;
    }

    public ReqUseKey getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqUseKey(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              token_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              key_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.KeysMessage.internal_static_Keys_ReqUseKey_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.KeysMessage.internal_static_Keys_ReqUseKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.KeysMessage.ReqUseKey.class, game.message.KeysMessage.ReqUseKey.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqUseKey> PARSER =
        new com.google.protobuf.AbstractParser<ReqUseKey>() {
      public ReqUseKey parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqUseKey(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqUseKey> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Keys.ReqUseKey.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 132201;</code>
       */
      eMsgID(0, 132201),
      ;

      /**
       * <code>eMsgID = 132201;</code>
       */
      public static final int eMsgID_VALUE = 132201;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 132201: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.KeysMessage.ReqUseKey.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Keys.ReqUseKey.MsgID)
    }

    private int bitField0_;
    // optional string token = 1;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private java.lang.Object token_;
    /**
     * <code>optional string token = 1;</code>
     *
     * <pre>
     * 从平台SDK中获取的访问令牌
     * </pre>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string token = 1;</code>
     *
     * <pre>
     * 从平台SDK中获取的访问令牌
     * </pre>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string token = 1;</code>
     *
     * <pre>
     * 从平台SDK中获取的访问令牌
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string key = 2;
    public static final int KEY_FIELD_NUMBER = 2;
    private java.lang.Object key_;
    /**
     * <code>required string key = 2;</code>
     *
     * <pre>
     * 激活码/兑换码的CODE
     * </pre>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string key = 2;</code>
     *
     * <pre>
     * 激活码/兑换码的CODE
     * </pre>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 2;</code>
     *
     * <pre>
     * 激活码/兑换码的CODE
     * </pre>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      token_ = "";
      key_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getKeyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTokenBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getKeyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.KeysMessage.ReqUseKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.KeysMessage.ReqUseKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.KeysMessage.ReqUseKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.KeysMessage.ReqUseKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.KeysMessage.ReqUseKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.KeysMessage.ReqUseKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.KeysMessage.ReqUseKey parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.KeysMessage.ReqUseKey parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.KeysMessage.ReqUseKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.KeysMessage.ReqUseKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.KeysMessage.ReqUseKey prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Keys.ReqUseKey}
     *
     * <pre>
     *客户端请求使用激活码/兑换码
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.KeysMessage.ReqUseKeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.KeysMessage.internal_static_Keys_ReqUseKey_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.KeysMessage.internal_static_Keys_ReqUseKey_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.KeysMessage.ReqUseKey.class, game.message.KeysMessage.ReqUseKey.Builder.class);
      }

      // Construct using game.message.KeysMessage.ReqUseKey.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.KeysMessage.internal_static_Keys_ReqUseKey_descriptor;
      }

      public game.message.KeysMessage.ReqUseKey getDefaultInstanceForType() {
        return game.message.KeysMessage.ReqUseKey.getDefaultInstance();
      }

      public game.message.KeysMessage.ReqUseKey build() {
        game.message.KeysMessage.ReqUseKey result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.KeysMessage.ReqUseKey buildPartial() {
        game.message.KeysMessage.ReqUseKey result = new game.message.KeysMessage.ReqUseKey(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.key_ = key_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.KeysMessage.ReqUseKey) {
          return mergeFrom((game.message.KeysMessage.ReqUseKey)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.KeysMessage.ReqUseKey other) {
        if (other == game.message.KeysMessage.ReqUseKey.getDefaultInstance()) return this;
        if (other.hasToken()) {
          bitField0_ |= 0x00000001;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasKey()) {
          bitField0_ |= 0x00000002;
          key_ = other.key_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.KeysMessage.ReqUseKey parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.KeysMessage.ReqUseKey) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string token = 1;
      private java.lang.Object token_ = "";
      /**
       * <code>optional string token = 1;</code>
       *
       * <pre>
       * 从平台SDK中获取的访问令牌
       * </pre>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string token = 1;</code>
       *
       * <pre>
       * 从平台SDK中获取的访问令牌
       * </pre>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string token = 1;</code>
       *
       * <pre>
       * 从平台SDK中获取的访问令牌
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 1;</code>
       *
       * <pre>
       * 从平台SDK中获取的访问令牌
       * </pre>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 1;</code>
       *
       * <pre>
       * 从平台SDK中获取的访问令牌
       * </pre>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 1;</code>
       *
       * <pre>
       * 从平台SDK中获取的访问令牌
       * </pre>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }

      // required string key = 2;
      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 2;</code>
       *
       * <pre>
       * 激活码/兑换码的CODE
       * </pre>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string key = 2;</code>
       *
       * <pre>
       * 激活码/兑换码的CODE
       * </pre>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 2;</code>
       *
       * <pre>
       * 激活码/兑换码的CODE
       * </pre>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 2;</code>
       *
       * <pre>
       * 激活码/兑换码的CODE
       * </pre>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 2;</code>
       *
       * <pre>
       * 激活码/兑换码的CODE
       * </pre>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 2;</code>
       *
       * <pre>
       * 激活码/兑换码的CODE
       * </pre>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        key_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Keys.ReqUseKey)
    }

    static {
      defaultInstance = new ReqUseKey(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Keys.ReqUseKey)
  }

  public interface ResUseKeyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 error = 1;
    /**
     * <code>optional int32 error = 1;</code>
     *
     * <pre>
     * 错误码，2000则表示操作成功
     * </pre>
     */
    boolean hasError();
    /**
     * <code>optional int32 error = 1;</code>
     *
     * <pre>
     * 错误码，2000则表示操作成功
     * </pre>
     */
    int getError();

    // optional string key = 2;
    /**
     * <code>optional string key = 2;</code>
     *
     * <pre>
     * 激活码/兑换码的CODE
     * </pre>
     */
    boolean hasKey();
    /**
     * <code>optional string key = 2;</code>
     *
     * <pre>
     * 激活码/兑换码的CODE
     * </pre>
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 2;</code>
     *
     * <pre>
     * 激活码/兑换码的CODE
     * </pre>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    // repeated .Backpack.Item items = 3;
    /**
     * <code>repeated .Backpack.Item items = 3;</code>
     *
     * <pre>
     * 使用后获得的物品列表
     * </pre>
     */
    java.util.List<game.message.BackpackMessage.Item> 
        getItemsList();
    /**
     * <code>repeated .Backpack.Item items = 3;</code>
     *
     * <pre>
     * 使用后获得的物品列表
     * </pre>
     */
    game.message.BackpackMessage.Item getItems(int index);
    /**
     * <code>repeated .Backpack.Item items = 3;</code>
     *
     * <pre>
     * 使用后获得的物品列表
     * </pre>
     */
    int getItemsCount();
    /**
     * <code>repeated .Backpack.Item items = 3;</code>
     *
     * <pre>
     * 使用后获得的物品列表
     * </pre>
     */
    java.util.List<? extends game.message.BackpackMessage.ItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .Backpack.Item items = 3;</code>
     *
     * <pre>
     * 使用后获得的物品列表
     * </pre>
     */
    game.message.BackpackMessage.ItemOrBuilder getItemsOrBuilder(
        int index);

    // repeated .Backpack.Resource resources = 4;
    /**
     * <code>repeated .Backpack.Resource resources = 4;</code>
     *
     * <pre>
     * 使用后获得资源列表
     * </pre>
     */
    java.util.List<game.message.BackpackMessage.Resource> 
        getResourcesList();
    /**
     * <code>repeated .Backpack.Resource resources = 4;</code>
     *
     * <pre>
     * 使用后获得资源列表
     * </pre>
     */
    game.message.BackpackMessage.Resource getResources(int index);
    /**
     * <code>repeated .Backpack.Resource resources = 4;</code>
     *
     * <pre>
     * 使用后获得资源列表
     * </pre>
     */
    int getResourcesCount();
    /**
     * <code>repeated .Backpack.Resource resources = 4;</code>
     *
     * <pre>
     * 使用后获得资源列表
     * </pre>
     */
    java.util.List<? extends game.message.BackpackMessage.ResourceOrBuilder> 
        getResourcesOrBuilderList();
    /**
     * <code>repeated .Backpack.Resource resources = 4;</code>
     *
     * <pre>
     * 使用后获得资源列表
     * </pre>
     */
    game.message.BackpackMessage.ResourceOrBuilder getResourcesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Keys.ResUseKey}
   *
   * <pre>
   *服务端回复使用激活码/兑换码
   * </pre>
   */
  public static final class ResUseKey extends
      com.google.protobuf.GeneratedMessage
      implements ResUseKeyOrBuilder {
    // Use ResUseKey.newBuilder() to construct.
    private ResUseKey(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResUseKey(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResUseKey defaultInstance;
    public static ResUseKey getDefaultInstance() {
      return defaultInstance;
    }

    public ResUseKey getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResUseKey(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              error_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              key_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                items_ = new java.util.ArrayList<game.message.BackpackMessage.Item>();
                mutable_bitField0_ |= 0x00000004;
              }
              items_.add(input.readMessage(game.message.BackpackMessage.Item.PARSER, extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                resources_ = new java.util.ArrayList<game.message.BackpackMessage.Resource>();
                mutable_bitField0_ |= 0x00000008;
              }
              resources_.add(input.readMessage(game.message.BackpackMessage.Resource.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          resources_ = java.util.Collections.unmodifiableList(resources_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.KeysMessage.internal_static_Keys_ResUseKey_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.KeysMessage.internal_static_Keys_ResUseKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.KeysMessage.ResUseKey.class, game.message.KeysMessage.ResUseKey.Builder.class);
    }

    public static com.google.protobuf.Parser<ResUseKey> PARSER =
        new com.google.protobuf.AbstractParser<ResUseKey>() {
      public ResUseKey parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResUseKey(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResUseKey> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Keys.ResUseKey.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 132101;</code>
       */
      eMsgID(0, 132101),
      ;

      /**
       * <code>eMsgID = 132101;</code>
       */
      public static final int eMsgID_VALUE = 132101;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 132101: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.KeysMessage.ResUseKey.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Keys.ResUseKey.MsgID)
    }

    private int bitField0_;
    // optional int32 error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private int error_;
    /**
     * <code>optional int32 error = 1;</code>
     *
     * <pre>
     * 错误码，2000则表示操作成功
     * </pre>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 error = 1;</code>
     *
     * <pre>
     * 错误码，2000则表示操作成功
     * </pre>
     */
    public int getError() {
      return error_;
    }

    // optional string key = 2;
    public static final int KEY_FIELD_NUMBER = 2;
    private java.lang.Object key_;
    /**
     * <code>optional string key = 2;</code>
     *
     * <pre>
     * 激活码/兑换码的CODE
     * </pre>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string key = 2;</code>
     *
     * <pre>
     * 激活码/兑换码的CODE
     * </pre>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key = 2;</code>
     *
     * <pre>
     * 激活码/兑换码的CODE
     * </pre>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .Backpack.Item items = 3;
    public static final int ITEMS_FIELD_NUMBER = 3;
    private java.util.List<game.message.BackpackMessage.Item> items_;
    /**
     * <code>repeated .Backpack.Item items = 3;</code>
     *
     * <pre>
     * 使用后获得的物品列表
     * </pre>
     */
    public java.util.List<game.message.BackpackMessage.Item> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .Backpack.Item items = 3;</code>
     *
     * <pre>
     * 使用后获得的物品列表
     * </pre>
     */
    public java.util.List<? extends game.message.BackpackMessage.ItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .Backpack.Item items = 3;</code>
     *
     * <pre>
     * 使用后获得的物品列表
     * </pre>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .Backpack.Item items = 3;</code>
     *
     * <pre>
     * 使用后获得的物品列表
     * </pre>
     */
    public game.message.BackpackMessage.Item getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .Backpack.Item items = 3;</code>
     *
     * <pre>
     * 使用后获得的物品列表
     * </pre>
     */
    public game.message.BackpackMessage.ItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    // repeated .Backpack.Resource resources = 4;
    public static final int RESOURCES_FIELD_NUMBER = 4;
    private java.util.List<game.message.BackpackMessage.Resource> resources_;
    /**
     * <code>repeated .Backpack.Resource resources = 4;</code>
     *
     * <pre>
     * 使用后获得资源列表
     * </pre>
     */
    public java.util.List<game.message.BackpackMessage.Resource> getResourcesList() {
      return resources_;
    }
    /**
     * <code>repeated .Backpack.Resource resources = 4;</code>
     *
     * <pre>
     * 使用后获得资源列表
     * </pre>
     */
    public java.util.List<? extends game.message.BackpackMessage.ResourceOrBuilder> 
        getResourcesOrBuilderList() {
      return resources_;
    }
    /**
     * <code>repeated .Backpack.Resource resources = 4;</code>
     *
     * <pre>
     * 使用后获得资源列表
     * </pre>
     */
    public int getResourcesCount() {
      return resources_.size();
    }
    /**
     * <code>repeated .Backpack.Resource resources = 4;</code>
     *
     * <pre>
     * 使用后获得资源列表
     * </pre>
     */
    public game.message.BackpackMessage.Resource getResources(int index) {
      return resources_.get(index);
    }
    /**
     * <code>repeated .Backpack.Resource resources = 4;</code>
     *
     * <pre>
     * 使用后获得资源列表
     * </pre>
     */
    public game.message.BackpackMessage.ResourceOrBuilder getResourcesOrBuilder(
        int index) {
      return resources_.get(index);
    }

    private void initFields() {
      error_ = 0;
      key_ = "";
      items_ = java.util.Collections.emptyList();
      resources_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getResourcesCount(); i++) {
        if (!getResources(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, error_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getKeyBytes());
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(3, items_.get(i));
      }
      for (int i = 0; i < resources_.size(); i++) {
        output.writeMessage(4, resources_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, error_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getKeyBytes());
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, items_.get(i));
      }
      for (int i = 0; i < resources_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, resources_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.KeysMessage.ResUseKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.KeysMessage.ResUseKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.KeysMessage.ResUseKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.KeysMessage.ResUseKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.KeysMessage.ResUseKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.KeysMessage.ResUseKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.KeysMessage.ResUseKey parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.KeysMessage.ResUseKey parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.KeysMessage.ResUseKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.KeysMessage.ResUseKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.KeysMessage.ResUseKey prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Keys.ResUseKey}
     *
     * <pre>
     *服务端回复使用激活码/兑换码
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.KeysMessage.ResUseKeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.KeysMessage.internal_static_Keys_ResUseKey_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.KeysMessage.internal_static_Keys_ResUseKey_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.KeysMessage.ResUseKey.class, game.message.KeysMessage.ResUseKey.Builder.class);
      }

      // Construct using game.message.KeysMessage.ResUseKey.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
          getResourcesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        error_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          itemsBuilder_.clear();
        }
        if (resourcesBuilder_ == null) {
          resources_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          resourcesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.KeysMessage.internal_static_Keys_ResUseKey_descriptor;
      }

      public game.message.KeysMessage.ResUseKey getDefaultInstanceForType() {
        return game.message.KeysMessage.ResUseKey.getDefaultInstance();
      }

      public game.message.KeysMessage.ResUseKey build() {
        game.message.KeysMessage.ResUseKey result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.KeysMessage.ResUseKey buildPartial() {
        game.message.KeysMessage.ResUseKey result = new game.message.KeysMessage.ResUseKey(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.key_ = key_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        if (resourcesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            resources_ = java.util.Collections.unmodifiableList(resources_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.resources_ = resources_;
        } else {
          result.resources_ = resourcesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.KeysMessage.ResUseKey) {
          return mergeFrom((game.message.KeysMessage.ResUseKey)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.KeysMessage.ResUseKey other) {
        if (other == game.message.KeysMessage.ResUseKey.getDefaultInstance()) return this;
        if (other.hasError()) {
          setError(other.getError());
        }
        if (other.hasKey()) {
          bitField0_ |= 0x00000002;
          key_ = other.key_;
          onChanged();
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000004);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        if (resourcesBuilder_ == null) {
          if (!other.resources_.isEmpty()) {
            if (resources_.isEmpty()) {
              resources_ = other.resources_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureResourcesIsMutable();
              resources_.addAll(other.resources_);
            }
            onChanged();
          }
        } else {
          if (!other.resources_.isEmpty()) {
            if (resourcesBuilder_.isEmpty()) {
              resourcesBuilder_.dispose();
              resourcesBuilder_ = null;
              resources_ = other.resources_;
              bitField0_ = (bitField0_ & ~0x00000008);
              resourcesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getResourcesFieldBuilder() : null;
            } else {
              resourcesBuilder_.addAllMessages(other.resources_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getResourcesCount(); i++) {
          if (!getResources(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.KeysMessage.ResUseKey parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.KeysMessage.ResUseKey) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 error = 1;
      private int error_ ;
      /**
       * <code>optional int32 error = 1;</code>
       *
       * <pre>
       * 错误码，2000则表示操作成功
       * </pre>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 error = 1;</code>
       *
       * <pre>
       * 错误码，2000则表示操作成功
       * </pre>
       */
      public int getError() {
        return error_;
      }
      /**
       * <code>optional int32 error = 1;</code>
       *
       * <pre>
       * 错误码，2000则表示操作成功
       * </pre>
       */
      public Builder setError(int value) {
        bitField0_ |= 0x00000001;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 error = 1;</code>
       *
       * <pre>
       * 错误码，2000则表示操作成功
       * </pre>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = 0;
        onChanged();
        return this;
      }

      // optional string key = 2;
      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 2;</code>
       *
       * <pre>
       * 激活码/兑换码的CODE
       * </pre>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string key = 2;</code>
       *
       * <pre>
       * 激活码/兑换码的CODE
       * </pre>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 2;</code>
       *
       * <pre>
       * 激活码/兑换码的CODE
       * </pre>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 2;</code>
       *
       * <pre>
       * 激活码/兑换码的CODE
       * </pre>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 2;</code>
       *
       * <pre>
       * 激活码/兑换码的CODE
       * </pre>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 2;</code>
       *
       * <pre>
       * 激活码/兑换码的CODE
       * </pre>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        key_ = value;
        onChanged();
        return this;
      }

      // repeated .Backpack.Item items = 3;
      private java.util.List<game.message.BackpackMessage.Item> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          items_ = new java.util.ArrayList<game.message.BackpackMessage.Item>(items_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          game.message.BackpackMessage.Item, game.message.BackpackMessage.Item.Builder, game.message.BackpackMessage.ItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public java.util.List<game.message.BackpackMessage.Item> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public game.message.BackpackMessage.Item getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public Builder setItems(
          int index, game.message.BackpackMessage.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public Builder setItems(
          int index, game.message.BackpackMessage.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public Builder addItems(game.message.BackpackMessage.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public Builder addItems(
          int index, game.message.BackpackMessage.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public Builder addItems(
          game.message.BackpackMessage.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public Builder addItems(
          int index, game.message.BackpackMessage.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends game.message.BackpackMessage.Item> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          super.addAll(values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public game.message.BackpackMessage.Item.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public game.message.BackpackMessage.ItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public java.util.List<? extends game.message.BackpackMessage.ItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public game.message.BackpackMessage.Item.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            game.message.BackpackMessage.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public game.message.BackpackMessage.Item.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, game.message.BackpackMessage.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .Backpack.Item items = 3;</code>
       *
       * <pre>
       * 使用后获得的物品列表
       * </pre>
       */
      public java.util.List<game.message.BackpackMessage.Item.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          game.message.BackpackMessage.Item, game.message.BackpackMessage.Item.Builder, game.message.BackpackMessage.ItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              game.message.BackpackMessage.Item, game.message.BackpackMessage.Item.Builder, game.message.BackpackMessage.ItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // repeated .Backpack.Resource resources = 4;
      private java.util.List<game.message.BackpackMessage.Resource> resources_ =
        java.util.Collections.emptyList();
      private void ensureResourcesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          resources_ = new java.util.ArrayList<game.message.BackpackMessage.Resource>(resources_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          game.message.BackpackMessage.Resource, game.message.BackpackMessage.Resource.Builder, game.message.BackpackMessage.ResourceOrBuilder> resourcesBuilder_;

      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public java.util.List<game.message.BackpackMessage.Resource> getResourcesList() {
        if (resourcesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(resources_);
        } else {
          return resourcesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public int getResourcesCount() {
        if (resourcesBuilder_ == null) {
          return resources_.size();
        } else {
          return resourcesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public game.message.BackpackMessage.Resource getResources(int index) {
        if (resourcesBuilder_ == null) {
          return resources_.get(index);
        } else {
          return resourcesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public Builder setResources(
          int index, game.message.BackpackMessage.Resource value) {
        if (resourcesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResourcesIsMutable();
          resources_.set(index, value);
          onChanged();
        } else {
          resourcesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public Builder setResources(
          int index, game.message.BackpackMessage.Resource.Builder builderForValue) {
        if (resourcesBuilder_ == null) {
          ensureResourcesIsMutable();
          resources_.set(index, builderForValue.build());
          onChanged();
        } else {
          resourcesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public Builder addResources(game.message.BackpackMessage.Resource value) {
        if (resourcesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResourcesIsMutable();
          resources_.add(value);
          onChanged();
        } else {
          resourcesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public Builder addResources(
          int index, game.message.BackpackMessage.Resource value) {
        if (resourcesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResourcesIsMutable();
          resources_.add(index, value);
          onChanged();
        } else {
          resourcesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public Builder addResources(
          game.message.BackpackMessage.Resource.Builder builderForValue) {
        if (resourcesBuilder_ == null) {
          ensureResourcesIsMutable();
          resources_.add(builderForValue.build());
          onChanged();
        } else {
          resourcesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public Builder addResources(
          int index, game.message.BackpackMessage.Resource.Builder builderForValue) {
        if (resourcesBuilder_ == null) {
          ensureResourcesIsMutable();
          resources_.add(index, builderForValue.build());
          onChanged();
        } else {
          resourcesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public Builder addAllResources(
          java.lang.Iterable<? extends game.message.BackpackMessage.Resource> values) {
        if (resourcesBuilder_ == null) {
          ensureResourcesIsMutable();
          super.addAll(values, resources_);
          onChanged();
        } else {
          resourcesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public Builder clearResources() {
        if (resourcesBuilder_ == null) {
          resources_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          resourcesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public Builder removeResources(int index) {
        if (resourcesBuilder_ == null) {
          ensureResourcesIsMutable();
          resources_.remove(index);
          onChanged();
        } else {
          resourcesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public game.message.BackpackMessage.Resource.Builder getResourcesBuilder(
          int index) {
        return getResourcesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public game.message.BackpackMessage.ResourceOrBuilder getResourcesOrBuilder(
          int index) {
        if (resourcesBuilder_ == null) {
          return resources_.get(index);  } else {
          return resourcesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public java.util.List<? extends game.message.BackpackMessage.ResourceOrBuilder> 
           getResourcesOrBuilderList() {
        if (resourcesBuilder_ != null) {
          return resourcesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(resources_);
        }
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public game.message.BackpackMessage.Resource.Builder addResourcesBuilder() {
        return getResourcesFieldBuilder().addBuilder(
            game.message.BackpackMessage.Resource.getDefaultInstance());
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public game.message.BackpackMessage.Resource.Builder addResourcesBuilder(
          int index) {
        return getResourcesFieldBuilder().addBuilder(
            index, game.message.BackpackMessage.Resource.getDefaultInstance());
      }
      /**
       * <code>repeated .Backpack.Resource resources = 4;</code>
       *
       * <pre>
       * 使用后获得资源列表
       * </pre>
       */
      public java.util.List<game.message.BackpackMessage.Resource.Builder> 
           getResourcesBuilderList() {
        return getResourcesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          game.message.BackpackMessage.Resource, game.message.BackpackMessage.Resource.Builder, game.message.BackpackMessage.ResourceOrBuilder> 
          getResourcesFieldBuilder() {
        if (resourcesBuilder_ == null) {
          resourcesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              game.message.BackpackMessage.Resource, game.message.BackpackMessage.Resource.Builder, game.message.BackpackMessage.ResourceOrBuilder>(
                  resources_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          resources_ = null;
        }
        return resourcesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Keys.ResUseKey)
    }

    static {
      defaultInstance = new ResUseKey(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Keys.ResUseKey)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Keys_ReqUseKey_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Keys_ReqUseKey_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Keys_ResUseKey_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Keys_ResUseKey_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nKeys.proto\022\004Keys\032\016Backpack.proto\">\n\tRe" +
      "qUseKey\022\r\n\005token\030\001 \001(\t\022\013\n\003key\030\002 \002(\t\"\025\n\005M" +
      "sgID\022\014\n\006eMsgID\020\351\210\010\"\204\001\n\tResUseKey\022\r\n\005erro" +
      "r\030\001 \001(\005\022\013\n\003key\030\002 \001(\t\022\035\n\005items\030\003 \003(\0132\016.Ba" +
      "ckpack.Item\022%\n\tresources\030\004 \003(\0132\022.Backpac" +
      "k.Resource\"\025\n\005MsgID\022\014\n\006eMsgID\020\205\210\010B\033\n\014gam" +
      "e.messageB\013KeysMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Keys_ReqUseKey_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Keys_ReqUseKey_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Keys_ReqUseKey_descriptor,
              new java.lang.String[] { "Token", "Key", });
          internal_static_Keys_ResUseKey_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Keys_ResUseKey_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Keys_ResUseKey_descriptor,
              new java.lang.String[] { "Error", "Key", "Items", "Resources", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          game.message.BackpackMessage.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
