// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewFeature.proto

package game.message;

public final class NewFeatureMessage {
  private NewFeatureMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FeatureInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string featureId = 1;
    /**
     * <code>required string featureId = 1;</code>
     *
     * <pre>
     * 功能ID
     * </pre>
     */
    boolean hasFeatureId();
    /**
     * <code>required string featureId = 1;</code>
     *
     * <pre>
     * 功能ID
     * </pre>
     */
    java.lang.String getFeatureId();
    /**
     * <code>required string featureId = 1;</code>
     *
     * <pre>
     * 功能ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getFeatureIdBytes();

    // required int32 featureState = 2;
    /**
     * <code>required int32 featureState = 2;</code>
     *
     * <pre>
     * 1 == 开启 2 == 未开启 3 == 新功能开放
     * </pre>
     */
    boolean hasFeatureState();
    /**
     * <code>required int32 featureState = 2;</code>
     *
     * <pre>
     * 1 == 开启 2 == 未开启 3 == 新功能开放
     * </pre>
     */
    int getFeatureState();

    // optional string reason = 3;
    /**
     * <code>optional string reason = 3;</code>
     *
     * <pre>
     * 未开启原因 
     * </pre>
     */
    boolean hasReason();
    /**
     * <code>optional string reason = 3;</code>
     *
     * <pre>
     * 未开启原因 
     * </pre>
     */
    java.lang.String getReason();
    /**
     * <code>optional string reason = 3;</code>
     *
     * <pre>
     * 未开启原因 
     * </pre>
     */
    com.google.protobuf.ByteString
        getReasonBytes();
  }
  /**
   * Protobuf type {@code NewFeature.FeatureInfo}
   *
   * <pre>
   *功能数据
   * </pre>
   */
  public static final class FeatureInfo extends
      com.google.protobuf.GeneratedMessage
      implements FeatureInfoOrBuilder {
    // Use FeatureInfo.newBuilder() to construct.
    private FeatureInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FeatureInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FeatureInfo defaultInstance;
    public static FeatureInfo getDefaultInstance() {
      return defaultInstance;
    }

    public FeatureInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FeatureInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              featureId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              featureState_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              reason_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.NewFeatureMessage.internal_static_NewFeature_FeatureInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.NewFeatureMessage.internal_static_NewFeature_FeatureInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.NewFeatureMessage.FeatureInfo.class, game.message.NewFeatureMessage.FeatureInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<FeatureInfo> PARSER =
        new com.google.protobuf.AbstractParser<FeatureInfo>() {
      public FeatureInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FeatureInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FeatureInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string featureId = 1;
    public static final int FEATUREID_FIELD_NUMBER = 1;
    private java.lang.Object featureId_;
    /**
     * <code>required string featureId = 1;</code>
     *
     * <pre>
     * 功能ID
     * </pre>
     */
    public boolean hasFeatureId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string featureId = 1;</code>
     *
     * <pre>
     * 功能ID
     * </pre>
     */
    public java.lang.String getFeatureId() {
      java.lang.Object ref = featureId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          featureId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string featureId = 1;</code>
     *
     * <pre>
     * 功能ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getFeatureIdBytes() {
      java.lang.Object ref = featureId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        featureId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 featureState = 2;
    public static final int FEATURESTATE_FIELD_NUMBER = 2;
    private int featureState_;
    /**
     * <code>required int32 featureState = 2;</code>
     *
     * <pre>
     * 1 == 开启 2 == 未开启 3 == 新功能开放
     * </pre>
     */
    public boolean hasFeatureState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 featureState = 2;</code>
     *
     * <pre>
     * 1 == 开启 2 == 未开启 3 == 新功能开放
     * </pre>
     */
    public int getFeatureState() {
      return featureState_;
    }

    // optional string reason = 3;
    public static final int REASON_FIELD_NUMBER = 3;
    private java.lang.Object reason_;
    /**
     * <code>optional string reason = 3;</code>
     *
     * <pre>
     * 未开启原因 
     * </pre>
     */
    public boolean hasReason() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string reason = 3;</code>
     *
     * <pre>
     * 未开启原因 
     * </pre>
     */
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          reason_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string reason = 3;</code>
     *
     * <pre>
     * 未开启原因 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      featureId_ = "";
      featureState_ = 0;
      reason_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFeatureId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFeatureState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFeatureIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, featureState_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getReasonBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFeatureIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, featureState_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getReasonBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.NewFeatureMessage.FeatureInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.NewFeatureMessage.FeatureInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.NewFeatureMessage.FeatureInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.NewFeatureMessage.FeatureInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.NewFeatureMessage.FeatureInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.NewFeatureMessage.FeatureInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.NewFeatureMessage.FeatureInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.NewFeatureMessage.FeatureInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.NewFeatureMessage.FeatureInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.NewFeatureMessage.FeatureInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.NewFeatureMessage.FeatureInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NewFeature.FeatureInfo}
     *
     * <pre>
     *功能数据
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.NewFeatureMessage.FeatureInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.NewFeatureMessage.internal_static_NewFeature_FeatureInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.NewFeatureMessage.internal_static_NewFeature_FeatureInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.NewFeatureMessage.FeatureInfo.class, game.message.NewFeatureMessage.FeatureInfo.Builder.class);
      }

      // Construct using game.message.NewFeatureMessage.FeatureInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        featureId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        featureState_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        reason_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.NewFeatureMessage.internal_static_NewFeature_FeatureInfo_descriptor;
      }

      public game.message.NewFeatureMessage.FeatureInfo getDefaultInstanceForType() {
        return game.message.NewFeatureMessage.FeatureInfo.getDefaultInstance();
      }

      public game.message.NewFeatureMessage.FeatureInfo build() {
        game.message.NewFeatureMessage.FeatureInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.NewFeatureMessage.FeatureInfo buildPartial() {
        game.message.NewFeatureMessage.FeatureInfo result = new game.message.NewFeatureMessage.FeatureInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.featureId_ = featureId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.featureState_ = featureState_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.reason_ = reason_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.NewFeatureMessage.FeatureInfo) {
          return mergeFrom((game.message.NewFeatureMessage.FeatureInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.NewFeatureMessage.FeatureInfo other) {
        if (other == game.message.NewFeatureMessage.FeatureInfo.getDefaultInstance()) return this;
        if (other.hasFeatureId()) {
          bitField0_ |= 0x00000001;
          featureId_ = other.featureId_;
          onChanged();
        }
        if (other.hasFeatureState()) {
          setFeatureState(other.getFeatureState());
        }
        if (other.hasReason()) {
          bitField0_ |= 0x00000004;
          reason_ = other.reason_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFeatureId()) {
          
          return false;
        }
        if (!hasFeatureState()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.NewFeatureMessage.FeatureInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.NewFeatureMessage.FeatureInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string featureId = 1;
      private java.lang.Object featureId_ = "";
      /**
       * <code>required string featureId = 1;</code>
       *
       * <pre>
       * 功能ID
       * </pre>
       */
      public boolean hasFeatureId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string featureId = 1;</code>
       *
       * <pre>
       * 功能ID
       * </pre>
       */
      public java.lang.String getFeatureId() {
        java.lang.Object ref = featureId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          featureId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string featureId = 1;</code>
       *
       * <pre>
       * 功能ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getFeatureIdBytes() {
        java.lang.Object ref = featureId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          featureId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string featureId = 1;</code>
       *
       * <pre>
       * 功能ID
       * </pre>
       */
      public Builder setFeatureId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        featureId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string featureId = 1;</code>
       *
       * <pre>
       * 功能ID
       * </pre>
       */
      public Builder clearFeatureId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        featureId_ = getDefaultInstance().getFeatureId();
        onChanged();
        return this;
      }
      /**
       * <code>required string featureId = 1;</code>
       *
       * <pre>
       * 功能ID
       * </pre>
       */
      public Builder setFeatureIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        featureId_ = value;
        onChanged();
        return this;
      }

      // required int32 featureState = 2;
      private int featureState_ ;
      /**
       * <code>required int32 featureState = 2;</code>
       *
       * <pre>
       * 1 == 开启 2 == 未开启 3 == 新功能开放
       * </pre>
       */
      public boolean hasFeatureState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 featureState = 2;</code>
       *
       * <pre>
       * 1 == 开启 2 == 未开启 3 == 新功能开放
       * </pre>
       */
      public int getFeatureState() {
        return featureState_;
      }
      /**
       * <code>required int32 featureState = 2;</code>
       *
       * <pre>
       * 1 == 开启 2 == 未开启 3 == 新功能开放
       * </pre>
       */
      public Builder setFeatureState(int value) {
        bitField0_ |= 0x00000002;
        featureState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 featureState = 2;</code>
       *
       * <pre>
       * 1 == 开启 2 == 未开启 3 == 新功能开放
       * </pre>
       */
      public Builder clearFeatureState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        featureState_ = 0;
        onChanged();
        return this;
      }

      // optional string reason = 3;
      private java.lang.Object reason_ = "";
      /**
       * <code>optional string reason = 3;</code>
       *
       * <pre>
       * 未开启原因 
       * </pre>
       */
      public boolean hasReason() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string reason = 3;</code>
       *
       * <pre>
       * 未开启原因 
       * </pre>
       */
      public java.lang.String getReason() {
        java.lang.Object ref = reason_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          reason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string reason = 3;</code>
       *
       * <pre>
       * 未开启原因 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getReasonBytes() {
        java.lang.Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string reason = 3;</code>
       *
       * <pre>
       * 未开启原因 
       * </pre>
       */
      public Builder setReason(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        reason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string reason = 3;</code>
       *
       * <pre>
       * 未开启原因 
       * </pre>
       */
      public Builder clearReason() {
        bitField0_ = (bitField0_ & ~0x00000004);
        reason_ = getDefaultInstance().getReason();
        onChanged();
        return this;
      }
      /**
       * <code>optional string reason = 3;</code>
       *
       * <pre>
       * 未开启原因 
       * </pre>
       */
      public Builder setReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        reason_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NewFeature.FeatureInfo)
    }

    static {
      defaultInstance = new FeatureInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NewFeature.FeatureInfo)
  }

  public interface ResFeatureInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .NewFeature.FeatureInfo info = 1;
    /**
     * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
     */
    java.util.List<game.message.NewFeatureMessage.FeatureInfo> 
        getInfoList();
    /**
     * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
     */
    game.message.NewFeatureMessage.FeatureInfo getInfo(int index);
    /**
     * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
     */
    int getInfoCount();
    /**
     * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
     */
    java.util.List<? extends game.message.NewFeatureMessage.FeatureInfoOrBuilder> 
        getInfoOrBuilderList();
    /**
     * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
     */
    game.message.NewFeatureMessage.FeatureInfoOrBuilder getInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code NewFeature.ResFeatureInfo}
   *
   * <pre>
   *服务器发送功能状态
   * </pre>
   */
  public static final class ResFeatureInfo extends
      com.google.protobuf.GeneratedMessage
      implements ResFeatureInfoOrBuilder {
    // Use ResFeatureInfo.newBuilder() to construct.
    private ResFeatureInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResFeatureInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResFeatureInfo defaultInstance;
    public static ResFeatureInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ResFeatureInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResFeatureInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                info_ = new java.util.ArrayList<game.message.NewFeatureMessage.FeatureInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              info_.add(input.readMessage(game.message.NewFeatureMessage.FeatureInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          info_ = java.util.Collections.unmodifiableList(info_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.NewFeatureMessage.internal_static_NewFeature_ResFeatureInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.NewFeatureMessage.internal_static_NewFeature_ResFeatureInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.NewFeatureMessage.ResFeatureInfo.class, game.message.NewFeatureMessage.ResFeatureInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ResFeatureInfo> PARSER =
        new com.google.protobuf.AbstractParser<ResFeatureInfo>() {
      public ResFeatureInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResFeatureInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResFeatureInfo> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code NewFeature.ResFeatureInfo.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 115101;</code>
       */
      eMsgID(0, 115101),
      ;

      /**
       * <code>eMsgID = 115101;</code>
       */
      public static final int eMsgID_VALUE = 115101;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 115101: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.NewFeatureMessage.ResFeatureInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:NewFeature.ResFeatureInfo.MsgID)
    }

    // repeated .NewFeature.FeatureInfo info = 1;
    public static final int INFO_FIELD_NUMBER = 1;
    private java.util.List<game.message.NewFeatureMessage.FeatureInfo> info_;
    /**
     * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
     */
    public java.util.List<game.message.NewFeatureMessage.FeatureInfo> getInfoList() {
      return info_;
    }
    /**
     * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
     */
    public java.util.List<? extends game.message.NewFeatureMessage.FeatureInfoOrBuilder> 
        getInfoOrBuilderList() {
      return info_;
    }
    /**
     * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
     */
    public int getInfoCount() {
      return info_.size();
    }
    /**
     * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
     */
    public game.message.NewFeatureMessage.FeatureInfo getInfo(int index) {
      return info_.get(index);
    }
    /**
     * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
     */
    public game.message.NewFeatureMessage.FeatureInfoOrBuilder getInfoOrBuilder(
        int index) {
      return info_.get(index);
    }

    private void initFields() {
      info_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getInfoCount(); i++) {
        if (!getInfo(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < info_.size(); i++) {
        output.writeMessage(1, info_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < info_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, info_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.NewFeatureMessage.ResFeatureInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.NewFeatureMessage.ResFeatureInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.NewFeatureMessage.ResFeatureInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.NewFeatureMessage.ResFeatureInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.NewFeatureMessage.ResFeatureInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.NewFeatureMessage.ResFeatureInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.NewFeatureMessage.ResFeatureInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.NewFeatureMessage.ResFeatureInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.NewFeatureMessage.ResFeatureInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.NewFeatureMessage.ResFeatureInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.NewFeatureMessage.ResFeatureInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NewFeature.ResFeatureInfo}
     *
     * <pre>
     *服务器发送功能状态
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.NewFeatureMessage.ResFeatureInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.NewFeatureMessage.internal_static_NewFeature_ResFeatureInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.NewFeatureMessage.internal_static_NewFeature_ResFeatureInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.NewFeatureMessage.ResFeatureInfo.class, game.message.NewFeatureMessage.ResFeatureInfo.Builder.class);
      }

      // Construct using game.message.NewFeatureMessage.ResFeatureInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          infoBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.NewFeatureMessage.internal_static_NewFeature_ResFeatureInfo_descriptor;
      }

      public game.message.NewFeatureMessage.ResFeatureInfo getDefaultInstanceForType() {
        return game.message.NewFeatureMessage.ResFeatureInfo.getDefaultInstance();
      }

      public game.message.NewFeatureMessage.ResFeatureInfo build() {
        game.message.NewFeatureMessage.ResFeatureInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.NewFeatureMessage.ResFeatureInfo buildPartial() {
        game.message.NewFeatureMessage.ResFeatureInfo result = new game.message.NewFeatureMessage.ResFeatureInfo(this);
        int from_bitField0_ = bitField0_;
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            info_ = java.util.Collections.unmodifiableList(info_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.NewFeatureMessage.ResFeatureInfo) {
          return mergeFrom((game.message.NewFeatureMessage.ResFeatureInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.NewFeatureMessage.ResFeatureInfo other) {
        if (other == game.message.NewFeatureMessage.ResFeatureInfo.getDefaultInstance()) return this;
        if (infoBuilder_ == null) {
          if (!other.info_.isEmpty()) {
            if (info_.isEmpty()) {
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInfoIsMutable();
              info_.addAll(other.info_);
            }
            onChanged();
          }
        } else {
          if (!other.info_.isEmpty()) {
            if (infoBuilder_.isEmpty()) {
              infoBuilder_.dispose();
              infoBuilder_ = null;
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000001);
              infoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInfoFieldBuilder() : null;
            } else {
              infoBuilder_.addAllMessages(other.info_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getInfoCount(); i++) {
          if (!getInfo(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.NewFeatureMessage.ResFeatureInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.NewFeatureMessage.ResFeatureInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .NewFeature.FeatureInfo info = 1;
      private java.util.List<game.message.NewFeatureMessage.FeatureInfo> info_ =
        java.util.Collections.emptyList();
      private void ensureInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          info_ = new java.util.ArrayList<game.message.NewFeatureMessage.FeatureInfo>(info_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          game.message.NewFeatureMessage.FeatureInfo, game.message.NewFeatureMessage.FeatureInfo.Builder, game.message.NewFeatureMessage.FeatureInfoOrBuilder> infoBuilder_;

      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public java.util.List<game.message.NewFeatureMessage.FeatureInfo> getInfoList() {
        if (infoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(info_);
        } else {
          return infoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public int getInfoCount() {
        if (infoBuilder_ == null) {
          return info_.size();
        } else {
          return infoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public game.message.NewFeatureMessage.FeatureInfo getInfo(int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);
        } else {
          return infoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public Builder setInfo(
          int index, game.message.NewFeatureMessage.FeatureInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.set(index, value);
          onChanged();
        } else {
          infoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public Builder setInfo(
          int index, game.message.NewFeatureMessage.FeatureInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.set(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public Builder addInfo(game.message.NewFeatureMessage.FeatureInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(value);
          onChanged();
        } else {
          infoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public Builder addInfo(
          int index, game.message.NewFeatureMessage.FeatureInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(index, value);
          onChanged();
        } else {
          infoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public Builder addInfo(
          game.message.NewFeatureMessage.FeatureInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public Builder addInfo(
          int index, game.message.NewFeatureMessage.FeatureInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public Builder addAllInfo(
          java.lang.Iterable<? extends game.message.NewFeatureMessage.FeatureInfo> values) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          super.addAll(values, info_);
          onChanged();
        } else {
          infoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public Builder removeInfo(int index) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.remove(index);
          onChanged();
        } else {
          infoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public game.message.NewFeatureMessage.FeatureInfo.Builder getInfoBuilder(
          int index) {
        return getInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public game.message.NewFeatureMessage.FeatureInfoOrBuilder getInfoOrBuilder(
          int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);  } else {
          return infoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public java.util.List<? extends game.message.NewFeatureMessage.FeatureInfoOrBuilder> 
           getInfoOrBuilderList() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(info_);
        }
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public game.message.NewFeatureMessage.FeatureInfo.Builder addInfoBuilder() {
        return getInfoFieldBuilder().addBuilder(
            game.message.NewFeatureMessage.FeatureInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public game.message.NewFeatureMessage.FeatureInfo.Builder addInfoBuilder(
          int index) {
        return getInfoFieldBuilder().addBuilder(
            index, game.message.NewFeatureMessage.FeatureInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .NewFeature.FeatureInfo info = 1;</code>
       */
      public java.util.List<game.message.NewFeatureMessage.FeatureInfo.Builder> 
           getInfoBuilderList() {
        return getInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          game.message.NewFeatureMessage.FeatureInfo, game.message.NewFeatureMessage.FeatureInfo.Builder, game.message.NewFeatureMessage.FeatureInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              game.message.NewFeatureMessage.FeatureInfo, game.message.NewFeatureMessage.FeatureInfo.Builder, game.message.NewFeatureMessage.FeatureInfoOrBuilder>(
                  info_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:NewFeature.ResFeatureInfo)
    }

    static {
      defaultInstance = new ResFeatureInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NewFeature.ResFeatureInfo)
  }

  public interface ResUpdateFeatureOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .NewFeature.FeatureInfo info = 1;
    /**
     * <code>required .NewFeature.FeatureInfo info = 1;</code>
     */
    boolean hasInfo();
    /**
     * <code>required .NewFeature.FeatureInfo info = 1;</code>
     */
    game.message.NewFeatureMessage.FeatureInfo getInfo();
    /**
     * <code>required .NewFeature.FeatureInfo info = 1;</code>
     */
    game.message.NewFeatureMessage.FeatureInfoOrBuilder getInfoOrBuilder();
  }
  /**
   * Protobuf type {@code NewFeature.ResUpdateFeature}
   *
   * <pre>
   *服务器发送功能更新
   * </pre>
   */
  public static final class ResUpdateFeature extends
      com.google.protobuf.GeneratedMessage
      implements ResUpdateFeatureOrBuilder {
    // Use ResUpdateFeature.newBuilder() to construct.
    private ResUpdateFeature(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResUpdateFeature(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResUpdateFeature defaultInstance;
    public static ResUpdateFeature getDefaultInstance() {
      return defaultInstance;
    }

    public ResUpdateFeature getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResUpdateFeature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              game.message.NewFeatureMessage.FeatureInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(game.message.NewFeatureMessage.FeatureInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.NewFeatureMessage.internal_static_NewFeature_ResUpdateFeature_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.NewFeatureMessage.internal_static_NewFeature_ResUpdateFeature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.NewFeatureMessage.ResUpdateFeature.class, game.message.NewFeatureMessage.ResUpdateFeature.Builder.class);
    }

    public static com.google.protobuf.Parser<ResUpdateFeature> PARSER =
        new com.google.protobuf.AbstractParser<ResUpdateFeature>() {
      public ResUpdateFeature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResUpdateFeature(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResUpdateFeature> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code NewFeature.ResUpdateFeature.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 115102;</code>
       */
      eMsgID(0, 115102),
      ;

      /**
       * <code>eMsgID = 115102;</code>
       */
      public static final int eMsgID_VALUE = 115102;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 115102: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.NewFeatureMessage.ResUpdateFeature.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:NewFeature.ResUpdateFeature.MsgID)
    }

    private int bitField0_;
    // required .NewFeature.FeatureInfo info = 1;
    public static final int INFO_FIELD_NUMBER = 1;
    private game.message.NewFeatureMessage.FeatureInfo info_;
    /**
     * <code>required .NewFeature.FeatureInfo info = 1;</code>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .NewFeature.FeatureInfo info = 1;</code>
     */
    public game.message.NewFeatureMessage.FeatureInfo getInfo() {
      return info_;
    }
    /**
     * <code>required .NewFeature.FeatureInfo info = 1;</code>
     */
    public game.message.NewFeatureMessage.FeatureInfoOrBuilder getInfoOrBuilder() {
      return info_;
    }

    private void initFields() {
      info_ = game.message.NewFeatureMessage.FeatureInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, info_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, info_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.NewFeatureMessage.ResUpdateFeature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.NewFeatureMessage.ResUpdateFeature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.NewFeatureMessage.ResUpdateFeature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.NewFeatureMessage.ResUpdateFeature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.NewFeatureMessage.ResUpdateFeature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.NewFeatureMessage.ResUpdateFeature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.NewFeatureMessage.ResUpdateFeature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.NewFeatureMessage.ResUpdateFeature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.NewFeatureMessage.ResUpdateFeature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.NewFeatureMessage.ResUpdateFeature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.NewFeatureMessage.ResUpdateFeature prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NewFeature.ResUpdateFeature}
     *
     * <pre>
     *服务器发送功能更新
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.NewFeatureMessage.ResUpdateFeatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.NewFeatureMessage.internal_static_NewFeature_ResUpdateFeature_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.NewFeatureMessage.internal_static_NewFeature_ResUpdateFeature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.NewFeatureMessage.ResUpdateFeature.class, game.message.NewFeatureMessage.ResUpdateFeature.Builder.class);
      }

      // Construct using game.message.NewFeatureMessage.ResUpdateFeature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (infoBuilder_ == null) {
          info_ = game.message.NewFeatureMessage.FeatureInfo.getDefaultInstance();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.NewFeatureMessage.internal_static_NewFeature_ResUpdateFeature_descriptor;
      }

      public game.message.NewFeatureMessage.ResUpdateFeature getDefaultInstanceForType() {
        return game.message.NewFeatureMessage.ResUpdateFeature.getDefaultInstance();
      }

      public game.message.NewFeatureMessage.ResUpdateFeature build() {
        game.message.NewFeatureMessage.ResUpdateFeature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.NewFeatureMessage.ResUpdateFeature buildPartial() {
        game.message.NewFeatureMessage.ResUpdateFeature result = new game.message.NewFeatureMessage.ResUpdateFeature(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.NewFeatureMessage.ResUpdateFeature) {
          return mergeFrom((game.message.NewFeatureMessage.ResUpdateFeature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.NewFeatureMessage.ResUpdateFeature other) {
        if (other == game.message.NewFeatureMessage.ResUpdateFeature.getDefaultInstance()) return this;
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInfo()) {
          
          return false;
        }
        if (!getInfo().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.NewFeatureMessage.ResUpdateFeature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.NewFeatureMessage.ResUpdateFeature) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .NewFeature.FeatureInfo info = 1;
      private game.message.NewFeatureMessage.FeatureInfo info_ = game.message.NewFeatureMessage.FeatureInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          game.message.NewFeatureMessage.FeatureInfo, game.message.NewFeatureMessage.FeatureInfo.Builder, game.message.NewFeatureMessage.FeatureInfoOrBuilder> infoBuilder_;
      /**
       * <code>required .NewFeature.FeatureInfo info = 1;</code>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .NewFeature.FeatureInfo info = 1;</code>
       */
      public game.message.NewFeatureMessage.FeatureInfo getInfo() {
        if (infoBuilder_ == null) {
          return info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .NewFeature.FeatureInfo info = 1;</code>
       */
      public Builder setInfo(game.message.NewFeatureMessage.FeatureInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .NewFeature.FeatureInfo info = 1;</code>
       */
      public Builder setInfo(
          game.message.NewFeatureMessage.FeatureInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .NewFeature.FeatureInfo info = 1;</code>
       */
      public Builder mergeInfo(game.message.NewFeatureMessage.FeatureInfo value) {
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              info_ != game.message.NewFeatureMessage.FeatureInfo.getDefaultInstance()) {
            info_ =
              game.message.NewFeatureMessage.FeatureInfo.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .NewFeature.FeatureInfo info = 1;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = game.message.NewFeatureMessage.FeatureInfo.getDefaultInstance();
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .NewFeature.FeatureInfo info = 1;</code>
       */
      public game.message.NewFeatureMessage.FeatureInfo.Builder getInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .NewFeature.FeatureInfo info = 1;</code>
       */
      public game.message.NewFeatureMessage.FeatureInfoOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_;
        }
      }
      /**
       * <code>required .NewFeature.FeatureInfo info = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          game.message.NewFeatureMessage.FeatureInfo, game.message.NewFeatureMessage.FeatureInfo.Builder, game.message.NewFeatureMessage.FeatureInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              game.message.NewFeatureMessage.FeatureInfo, game.message.NewFeatureMessage.FeatureInfo.Builder, game.message.NewFeatureMessage.FeatureInfoOrBuilder>(
                  info_,
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:NewFeature.ResUpdateFeature)
    }

    static {
      defaultInstance = new ResUpdateFeature(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NewFeature.ResUpdateFeature)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NewFeature_FeatureInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NewFeature_FeatureInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NewFeature_ResFeatureInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NewFeature_ResFeatureInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NewFeature_ResUpdateFeature_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NewFeature_ResUpdateFeature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020NewFeature.proto\022\nNewFeature\"F\n\013Featur" +
      "eInfo\022\021\n\tfeatureId\030\001 \002(\t\022\024\n\014featureState" +
      "\030\002 \002(\005\022\016\n\006reason\030\003 \001(\t\"N\n\016ResFeatureInfo" +
      "\022%\n\004info\030\001 \003(\0132\027.NewFeature.FeatureInfo\"" +
      "\025\n\005MsgID\022\014\n\006eMsgID\020\235\203\007\"P\n\020ResUpdateFeatu" +
      "re\022%\n\004info\030\001 \002(\0132\027.NewFeature.FeatureInf" +
      "o\"\025\n\005MsgID\022\014\n\006eMsgID\020\236\203\007B!\n\014game.message" +
      "B\021NewFeatureMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NewFeature_FeatureInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NewFeature_FeatureInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NewFeature_FeatureInfo_descriptor,
              new java.lang.String[] { "FeatureId", "FeatureState", "Reason", });
          internal_static_NewFeature_ResFeatureInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_NewFeature_ResFeatureInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NewFeature_ResFeatureInfo_descriptor,
              new java.lang.String[] { "Info", });
          internal_static_NewFeature_ResUpdateFeature_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_NewFeature_ResUpdateFeature_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NewFeature_ResUpdateFeature_descriptor,
              new java.lang.String[] { "Info", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
