// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Notify.proto

package game.message;

public final class NotifyMessage {
  private NotifyMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ResNotifyPlayerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 notifyType = 1;
    /**
     * <code>required int32 notifyType = 1;</code>
     *
     * <pre>
     * 提示类型 0 = error，1 = success， 2 = normal	
     * </pre>
     */
    boolean hasNotifyType();
    /**
     * <code>required int32 notifyType = 1;</code>
     *
     * <pre>
     * 提示类型 0 = error，1 = success， 2 = normal	
     * </pre>
     */
    int getNotifyType();

    // required string context = 2;
    /**
     * <code>required string context = 2;</code>
     *
     * <pre>
     * 提示内容
     * </pre>
     */
    boolean hasContext();
    /**
     * <code>required string context = 2;</code>
     *
     * <pre>
     * 提示内容
     * </pre>
     */
    java.lang.String getContext();
    /**
     * <code>required string context = 2;</code>
     *
     * <pre>
     * 提示内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getContextBytes();
  }
  /**
   * Protobuf type {@code Notify.ResNotifyPlayer}
   *
   * <pre>
   * 提示消息
   * </pre>
   */
  public static final class ResNotifyPlayer extends
      com.google.protobuf.GeneratedMessage
      implements ResNotifyPlayerOrBuilder {
    // Use ResNotifyPlayer.newBuilder() to construct.
    private ResNotifyPlayer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResNotifyPlayer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResNotifyPlayer defaultInstance;
    public static ResNotifyPlayer getDefaultInstance() {
      return defaultInstance;
    }

    public ResNotifyPlayer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResNotifyPlayer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              notifyType_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              context_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.NotifyMessage.internal_static_Notify_ResNotifyPlayer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.NotifyMessage.internal_static_Notify_ResNotifyPlayer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.NotifyMessage.ResNotifyPlayer.class, game.message.NotifyMessage.ResNotifyPlayer.Builder.class);
    }

    public static com.google.protobuf.Parser<ResNotifyPlayer> PARSER =
        new com.google.protobuf.AbstractParser<ResNotifyPlayer>() {
      public ResNotifyPlayer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResNotifyPlayer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResNotifyPlayer> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Notify.ResNotifyPlayer.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 118101;</code>
       */
      eMsgID(0, 118101),
      ;

      /**
       * <code>eMsgID = 118101;</code>
       */
      public static final int eMsgID_VALUE = 118101;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 118101: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.NotifyMessage.ResNotifyPlayer.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Notify.ResNotifyPlayer.MsgID)
    }

    private int bitField0_;
    // required int32 notifyType = 1;
    public static final int NOTIFYTYPE_FIELD_NUMBER = 1;
    private int notifyType_;
    /**
     * <code>required int32 notifyType = 1;</code>
     *
     * <pre>
     * 提示类型 0 = error，1 = success， 2 = normal	
     * </pre>
     */
    public boolean hasNotifyType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 notifyType = 1;</code>
     *
     * <pre>
     * 提示类型 0 = error，1 = success， 2 = normal	
     * </pre>
     */
    public int getNotifyType() {
      return notifyType_;
    }

    // required string context = 2;
    public static final int CONTEXT_FIELD_NUMBER = 2;
    private java.lang.Object context_;
    /**
     * <code>required string context = 2;</code>
     *
     * <pre>
     * 提示内容
     * </pre>
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string context = 2;</code>
     *
     * <pre>
     * 提示内容
     * </pre>
     */
    public java.lang.String getContext() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          context_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string context = 2;</code>
     *
     * <pre>
     * 提示内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      notifyType_ = 0;
      context_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNotifyType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContext()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, notifyType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getContextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, notifyType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getContextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.NotifyMessage.ResNotifyPlayer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.NotifyMessage.ResNotifyPlayer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.NotifyMessage.ResNotifyPlayer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.NotifyMessage.ResNotifyPlayer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.NotifyMessage.ResNotifyPlayer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.NotifyMessage.ResNotifyPlayer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.NotifyMessage.ResNotifyPlayer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.NotifyMessage.ResNotifyPlayer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.NotifyMessage.ResNotifyPlayer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.NotifyMessage.ResNotifyPlayer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.NotifyMessage.ResNotifyPlayer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Notify.ResNotifyPlayer}
     *
     * <pre>
     * 提示消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.NotifyMessage.ResNotifyPlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.NotifyMessage.internal_static_Notify_ResNotifyPlayer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.NotifyMessage.internal_static_Notify_ResNotifyPlayer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.NotifyMessage.ResNotifyPlayer.class, game.message.NotifyMessage.ResNotifyPlayer.Builder.class);
      }

      // Construct using game.message.NotifyMessage.ResNotifyPlayer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        notifyType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        context_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.NotifyMessage.internal_static_Notify_ResNotifyPlayer_descriptor;
      }

      public game.message.NotifyMessage.ResNotifyPlayer getDefaultInstanceForType() {
        return game.message.NotifyMessage.ResNotifyPlayer.getDefaultInstance();
      }

      public game.message.NotifyMessage.ResNotifyPlayer build() {
        game.message.NotifyMessage.ResNotifyPlayer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.NotifyMessage.ResNotifyPlayer buildPartial() {
        game.message.NotifyMessage.ResNotifyPlayer result = new game.message.NotifyMessage.ResNotifyPlayer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.notifyType_ = notifyType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.context_ = context_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.NotifyMessage.ResNotifyPlayer) {
          return mergeFrom((game.message.NotifyMessage.ResNotifyPlayer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.NotifyMessage.ResNotifyPlayer other) {
        if (other == game.message.NotifyMessage.ResNotifyPlayer.getDefaultInstance()) return this;
        if (other.hasNotifyType()) {
          setNotifyType(other.getNotifyType());
        }
        if (other.hasContext()) {
          bitField0_ |= 0x00000002;
          context_ = other.context_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNotifyType()) {
          
          return false;
        }
        if (!hasContext()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.NotifyMessage.ResNotifyPlayer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.NotifyMessage.ResNotifyPlayer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 notifyType = 1;
      private int notifyType_ ;
      /**
       * <code>required int32 notifyType = 1;</code>
       *
       * <pre>
       * 提示类型 0 = error，1 = success， 2 = normal	
       * </pre>
       */
      public boolean hasNotifyType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 notifyType = 1;</code>
       *
       * <pre>
       * 提示类型 0 = error，1 = success， 2 = normal	
       * </pre>
       */
      public int getNotifyType() {
        return notifyType_;
      }
      /**
       * <code>required int32 notifyType = 1;</code>
       *
       * <pre>
       * 提示类型 0 = error，1 = success， 2 = normal	
       * </pre>
       */
      public Builder setNotifyType(int value) {
        bitField0_ |= 0x00000001;
        notifyType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 notifyType = 1;</code>
       *
       * <pre>
       * 提示类型 0 = error，1 = success， 2 = normal	
       * </pre>
       */
      public Builder clearNotifyType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        notifyType_ = 0;
        onChanged();
        return this;
      }

      // required string context = 2;
      private java.lang.Object context_ = "";
      /**
       * <code>required string context = 2;</code>
       *
       * <pre>
       * 提示内容
       * </pre>
       */
      public boolean hasContext() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string context = 2;</code>
       *
       * <pre>
       * 提示内容
       * </pre>
       */
      public java.lang.String getContext() {
        java.lang.Object ref = context_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          context_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string context = 2;</code>
       *
       * <pre>
       * 提示内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContextBytes() {
        java.lang.Object ref = context_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          context_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string context = 2;</code>
       *
       * <pre>
       * 提示内容
       * </pre>
       */
      public Builder setContext(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        context_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 2;</code>
       *
       * <pre>
       * 提示内容
       * </pre>
       */
      public Builder clearContext() {
        bitField0_ = (bitField0_ & ~0x00000002);
        context_ = getDefaultInstance().getContext();
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 2;</code>
       *
       * <pre>
       * 提示内容
       * </pre>
       */
      public Builder setContextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        context_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Notify.ResNotifyPlayer)
    }

    static {
      defaultInstance = new ResNotifyPlayer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Notify.ResNotifyPlayer)
  }

  public interface ResNotifyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string context = 1;
    /**
     * <code>required string context = 1;</code>
     *
     * <pre>
     * 公告内容		
     * </pre>
     */
    boolean hasContext();
    /**
     * <code>required string context = 1;</code>
     *
     * <pre>
     * 公告内容		
     * </pre>
     */
    java.lang.String getContext();
    /**
     * <code>required string context = 1;</code>
     *
     * <pre>
     * 公告内容		
     * </pre>
     */
    com.google.protobuf.ByteString
        getContextBytes();
  }
  /**
   * Protobuf type {@code Notify.ResNotify}
   *
   * <pre>
   * 走马灯公告
   * </pre>
   */
  public static final class ResNotify extends
      com.google.protobuf.GeneratedMessage
      implements ResNotifyOrBuilder {
    // Use ResNotify.newBuilder() to construct.
    private ResNotify(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResNotify(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResNotify defaultInstance;
    public static ResNotify getDefaultInstance() {
      return defaultInstance;
    }

    public ResNotify getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResNotify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              context_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.message.NotifyMessage.internal_static_Notify_ResNotify_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.message.NotifyMessage.internal_static_Notify_ResNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.message.NotifyMessage.ResNotify.class, game.message.NotifyMessage.ResNotify.Builder.class);
    }

    public static com.google.protobuf.Parser<ResNotify> PARSER =
        new com.google.protobuf.AbstractParser<ResNotify>() {
      public ResNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResNotify(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResNotify> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Notify.ResNotify.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 118102;</code>
       */
      eMsgID(0, 118102),
      ;

      /**
       * <code>eMsgID = 118102;</code>
       */
      public static final int eMsgID_VALUE = 118102;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 118102: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return game.message.NotifyMessage.ResNotify.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Notify.ResNotify.MsgID)
    }

    private int bitField0_;
    // required string context = 1;
    public static final int CONTEXT_FIELD_NUMBER = 1;
    private java.lang.Object context_;
    /**
     * <code>required string context = 1;</code>
     *
     * <pre>
     * 公告内容		
     * </pre>
     */
    public boolean hasContext() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string context = 1;</code>
     *
     * <pre>
     * 公告内容		
     * </pre>
     */
    public java.lang.String getContext() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          context_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string context = 1;</code>
     *
     * <pre>
     * 公告内容		
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      context_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasContext()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getContextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getContextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static game.message.NotifyMessage.ResNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.NotifyMessage.ResNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.NotifyMessage.ResNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.message.NotifyMessage.ResNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.message.NotifyMessage.ResNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.NotifyMessage.ResNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static game.message.NotifyMessage.ResNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static game.message.NotifyMessage.ResNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static game.message.NotifyMessage.ResNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static game.message.NotifyMessage.ResNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(game.message.NotifyMessage.ResNotify prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Notify.ResNotify}
     *
     * <pre>
     * 走马灯公告
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements game.message.NotifyMessage.ResNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.message.NotifyMessage.internal_static_Notify_ResNotify_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.message.NotifyMessage.internal_static_Notify_ResNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.message.NotifyMessage.ResNotify.class, game.message.NotifyMessage.ResNotify.Builder.class);
      }

      // Construct using game.message.NotifyMessage.ResNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        context_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.message.NotifyMessage.internal_static_Notify_ResNotify_descriptor;
      }

      public game.message.NotifyMessage.ResNotify getDefaultInstanceForType() {
        return game.message.NotifyMessage.ResNotify.getDefaultInstance();
      }

      public game.message.NotifyMessage.ResNotify build() {
        game.message.NotifyMessage.ResNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public game.message.NotifyMessage.ResNotify buildPartial() {
        game.message.NotifyMessage.ResNotify result = new game.message.NotifyMessage.ResNotify(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.context_ = context_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.message.NotifyMessage.ResNotify) {
          return mergeFrom((game.message.NotifyMessage.ResNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.message.NotifyMessage.ResNotify other) {
        if (other == game.message.NotifyMessage.ResNotify.getDefaultInstance()) return this;
        if (other.hasContext()) {
          bitField0_ |= 0x00000001;
          context_ = other.context_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContext()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        game.message.NotifyMessage.ResNotify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (game.message.NotifyMessage.ResNotify) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string context = 1;
      private java.lang.Object context_ = "";
      /**
       * <code>required string context = 1;</code>
       *
       * <pre>
       * 公告内容		
       * </pre>
       */
      public boolean hasContext() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string context = 1;</code>
       *
       * <pre>
       * 公告内容		
       * </pre>
       */
      public java.lang.String getContext() {
        java.lang.Object ref = context_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          context_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string context = 1;</code>
       *
       * <pre>
       * 公告内容		
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContextBytes() {
        java.lang.Object ref = context_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          context_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string context = 1;</code>
       *
       * <pre>
       * 公告内容		
       * </pre>
       */
      public Builder setContext(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        context_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 1;</code>
       *
       * <pre>
       * 公告内容		
       * </pre>
       */
      public Builder clearContext() {
        bitField0_ = (bitField0_ & ~0x00000001);
        context_ = getDefaultInstance().getContext();
        onChanged();
        return this;
      }
      /**
       * <code>required string context = 1;</code>
       *
       * <pre>
       * 公告内容		
       * </pre>
       */
      public Builder setContextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        context_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Notify.ResNotify)
    }

    static {
      defaultInstance = new ResNotify(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Notify.ResNotify)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Notify_ResNotifyPlayer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Notify_ResNotifyPlayer_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Notify_ResNotify_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Notify_ResNotify_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Notify.proto\022\006Notify\"M\n\017ResNotifyPlaye" +
      "r\022\022\n\nnotifyType\030\001 \002(\005\022\017\n\007context\030\002 \002(\t\"\025" +
      "\n\005MsgID\022\014\n\006eMsgID\020\325\232\007\"3\n\tResNotify\022\017\n\007co" +
      "ntext\030\001 \002(\t\"\025\n\005MsgID\022\014\n\006eMsgID\020\326\232\007B\035\n\014ga" +
      "me.messageB\rNotifyMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Notify_ResNotifyPlayer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Notify_ResNotifyPlayer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Notify_ResNotifyPlayer_descriptor,
              new java.lang.String[] { "NotifyType", "Context", });
          internal_static_Notify_ResNotify_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Notify_ResNotify_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Notify_ResNotify_descriptor,
              new java.lang.String[] { "Context", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
